#pragma config(Sensor, in1,    LFR,            sensorLineFollower)
#pragma config(Sensor, in2,    LFM,            sensorLineFollower)
#pragma config(Sensor, in3,    LFL,            sensorLineFollower)
#pragma config(Sensor, in4,    Pot,            sensorPotentiometer)
#pragma config(Sensor, dgtl2,  Sonar,          sensorSONAR_inch)
#pragma config(Sensor, dgtl5,  Button,         sensorTouch)
#pragma config(Sensor, dgtl6,  LEDRed,         sensorLEDtoVCC)
#pragma config(Sensor, dgtl7,  LEDYellow,      sensorLEDtoVCC)
#pragma config(Sensor, dgtl8,  LEDGreen,       sensorLEDtoVCC)
#pragma config(Sensor, dgtl9,  RightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl11, LeftEncoder,    sensorQuadEncoder)
#pragma config(Motor,  port1,           Flashlight,    tmotorVexFlashlight, openLoop, reversed)
#pragma config(Motor,  port2,           RightMotor,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           LeftMotor,     tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
/*
When the button is pushed the yellow LED will switch to red LED.
Green LED is on waiting for Button to be pushed
Yellow LED turn on for 5 seconds then turns off
Red LED turn on for 5 seconds then turns off
Green LED turns on and waits until the button is pushed.
*/

task main()
{
	//could turn off all LED's to make sure they are set and ready to go
	while (1==1)
	{
		turnLEDOn(LEDGreen);
		while (SensorValue[Button]==0)
		{}//this is the body because there isn't a command while we are waiting.
		turnLEDOff(LEDGreen);
		turnLEDOn(LEDYellow);
		waitInMilliseconds(1000);
		turnLEDOff(LEDYellow);
		turnLEDOn(LEDRed);
		waitInMilliseconds(1000);
		turnLEDOff(LEDRed);

	}



}
