#pragma config(Sensor, in1,    LFR,            sensorLineFollower)
#pragma config(Sensor, in2,    LFM,            sensorLineFollower)
#pragma config(Sensor, in3,    LFL,            sensorLineFollower)
#pragma config(Sensor, in4,    Pot,            sensorPotentiometer)
#pragma config(Sensor, dgtl2,  Sonar,          sensorSONAR_inch)
#pragma config(Sensor, dgtl5,  Button,         sensorTouch)
#pragma config(Sensor, dgtl6,  LEDRed,         sensorLEDtoVCC)
#pragma config(Sensor, dgtl7,  LEDYellow,      sensorLEDtoVCC)
#pragma config(Sensor, dgtl8,  LEDGreen,       sensorLEDtoVCC)
#pragma config(Sensor, dgtl9,  RightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl11, LeftEncoder,    sensorQuadEncoder)
#pragma config(Motor,  port1,           Flashlight,    tmotorVexFlashlight, openLoop, reversed)
#pragma config(Motor,  port2,           RightMotor,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           LeftMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           Servo1,        tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(1 == 1)
	{
		startMotor(port2, 50);
		delay(3000);
		startMotor(port2, -127);
		delay(2000);
		stopMotor(port2);

		startMotor(port3, -100);
		delay(2000);
		stopMotor(port3);

		turnLEDOn(LEDRed);
		delay(1000);
		turnLEDOff(LEDRed);
		waitInMilliseconds(1000);

		turnLEDOn(LEDGreen);
		delay(1000);
		turnLEDOff(LEDGreen);

		turnFlashlightOn(port1, 10);
		delay (1000);
		turnFlashlightOn(port1, 50);
		delay(1000);
		turnFlashlightOn(port1, 127);
		delay(1000);
		turnFlashlightOn(port1, 50);
		delay(1000);
		turnFlashlightOn(port1, 10);
		delay(1000);
		turnFlashlightOff(port1);

		setServo(port4, 127);
		delay (3000);
		setServo(port4, -127);
		delay(3000);
		setServo(port4, 0);


	}


}
