#pragma config(Sensor, in1,    LFR,            sensorLineFollower)
#pragma config(Sensor, in2,    LFM,            sensorLineFollower)
#pragma config(Sensor, in3,    LFL,            sensorLineFollower)
#pragma config(Sensor, in4,    Pot,            sensorPotentiometer)
#pragma config(Sensor, dgtl2,  Sonar,          sensorSONAR_inch)
#pragma config(Sensor, dgtl5,  Button,         sensorTouch)
#pragma config(Sensor, dgtl6,  LEDRed,         sensorLEDtoVCC)
#pragma config(Sensor, dgtl7,  LEDYellow,      sensorLEDtoVCC)
#pragma config(Sensor, dgtl8,  LEDGreen,       sensorLEDtoVCC)
#pragma config(Sensor, dgtl9,  RightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl11, LeftEncoder,    sensorQuadEncoder)
#pragma config(Motor,  port1,           Flashlight,    tmotorVexFlashlight, openLoop, reversed)
#pragma config(Motor,  port2,           RightMotor,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           LeftMotor,     tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
/*
This is a good program to show students how FAST the Cortex responds.
Switch closures are very noisy events.
The signal can go from Hi to Low back to high many times during a single switch press.
In this program each time the button is pressed a "counter" is incremented.
See that Counts increments more than once each button press.
*/
int counter=0;
int SW;//switch
task main()
{
	while (1==1)
	{
		SW=SensorValue[Button];
		if (SW==1) counter++;
		waitInMilliseconds(20);// This allows for time between the jumps of electrons.
		while (SW==1)
		{
			SW=SensorValue[Button];//Leave this out and see what happens. What happens if I didn't put this step in.
		}
		//waitInMilliseconds(20);// This allows for time between the jumps of electrons.
	}


}
